### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by efruchter** [jwien001/LiarsDice#1]
Going to add a favicon, as well as a resource loader to pull the image from the jar file.
Work will be done in the favicon branch. Will work on getting a fancy icon setup for the OSX dock.

**Comment by jwien001** [comment]
Fixed in fc225bf467df5f29a0ac2d2487ada4d6215de0ba

**Comment by efruchter** [comment]
Doesn't work on mac, and is currently broken in master.
Going to get it working on mac docks in a separate branch. For now, I'll leave master alone.
